const LENGTH_PHOTO_DATAS = 25;
const LENGHT_COMMENTS = 150;
const START_NUM = 1;
const AVATAR_END_NUM = 6;
const LIKE_START_NUM = 15;
const LIKE_END_NUM = 200;
const COMMENT_END_NUM = 3;

export { LENGTH_PHOTO_DATAS, LENGHT_COMMENTS, START_NUM, AVATAR_END_NUM, LIKE_START_NUM, LIKE_END_NUM, COMMENT_END_NUM };
